debounced the button reading
parzival0152/ktane-irl pull request #8
Opened 2024-10-16 11:15 UTC by parzival0152

2024-10-16 12:12 UTC, Mipsters requested changes

2024-10-16 12:12 UTC, Mipsters commented on morse_module/morse.c
> +		if(inc_count > 5) {
constify the shit

2024-10-16 12:12 UTC, Mipsters commented on morse_module/morse.c
> +		sleep_ms(20);
more constify

2024-10-16 12:40 UTC, parzival0152 commented on morse_module/morse.c
> +		if(inc_count > 5) {
consted

2024-10-16 13:29 UTC, Mipsters requested changes

2024-10-16 13:29 UTC, Mipsters commented on morse_module/morse.c
> +const uint8_t debounce_factor = 5;
uppercase

2024-10-17 15:32 UTC, Mipsters approved these changes

2024-10-17 15:34 UTC, merged